version: '3.8'

services:
  app:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    container_name: to-do-app-container
    ports:
    - 8000:8000
    tty: true
    stdin_open: true